version: '3'
services:
    redis:
      image: 'redis:6.2.5'
      container_name: redis
      command: ["--notify-keyspace-events", "Ex"]
      ports:
        - 6379:6379
      networks:
        - droneshield
    producer:
      build:
        dockerfile: Dockerfile
        context: './producer'
      container_name: 'producer'
      networks:
        - droneshield
networks:
    droneshield:
  
